### ISSUE TITLE
Idea: separate navigation and sail behaviors 

### ISSUE THREAD

**Issue by kragniz** [abersailbot/dewi-behaviour#14]
@TomGC96 had the idea of separating the logic of sailing and navigation into two separate behaviors. This is an interesting idea and probably worth considering.

**Comment by colinsauze** [comment]
A lot of other teams have followed this approach. The problem is where exactly do you draw the boundary and how do you deal with things that need to communicate across that boundary. I presume sailing means the second by second control of the rudder and sail, while navigation means finding the heading to the waypoint? Where would tacking fit? what about collision avoidance?

**Comment by kragniz** [comment]
@colinsauze actually, I worded the issue badly. The idea was to separate sail control and rudder control.

**Comment by colinsauze** [comment]
ok, there is still some interaction between them such as tacking. Our existing tacking strategies have been quite naive, just altering the target heading and letting the rudder control take car of making the turn. You may find (especially on Kitty) that you can optimise your tacking by doing more coordination between the sail and rudder during the manoeuvre. Doing a smaller initial rudder movement may result in less reduction in speed and a faster tack, suddenly jumping a target heading by 90 degrees will result in a full scale rudder movement in the current code. But during normal sailing if you suddenly find yourself 90 degrees off course you might want a large rudder movement. 

The other area where a lot of interaction is required is if you want to start using the sail to help with steering. We did this on one of the original MOOPs and it made for much better heading control, especially in high winds.

**Comment by TomGC96** [comment]
I think it wasn't so much that we do them totally independently, but that they CAN run independently e.g. if we wanted to control the rudder only, the sail would adjust itself. It's a good point though you can use the sail to speed up the turn, but at this point with Dewi, there are better places to gain sailing speed in the code. It might not work, but worst case is we go back to the current way of doing it. We'll see what happens.

**Comment by colinsauze** [comment]
It will still be possible to coordinate them with them as independent behaviours. You just need to think about how much communication goes on between them and whether having two behaviours will just make things more complicated, harder to debug and harder to follow. On the other hand I can see the attraction of just being able to disable the sail behaviour to test rudder control and if there isn't too much communication it might make code easier to follow.

**Comment by colinsauze** [comment]
I guess the other advantage is that you don't need to set the sail as frequently as the rudder. Some of my previous control systems had code to track when the sail was last adjusted and only set it if a certain amount of time had passed. Having two behaviours might make this sort of thing a bit cleaner. Perhaps boatd also needs some kind of timer callback to run code at a certain interval.

**Comment by kragniz** [comment]
The current architecture does not really suit this. Tacking and sail control are linked.
