### ISSUE TITLE
Write and test a fallback behaviour

### ISSUE THREAD

**Issue by kragniz** [abersailbot/dewi-behaviour#17]
A basic and fairly untested idle behvaiour was removed in 8d3c91ebd6be58d0b12ac1a1a711994f39ed039a. This code was a little outdated due to some python-boatdclient changes and could do with a re-think.

Implement a new behaviour to be run when no other behaviour is running.

**Comment by Tebazil12** [comment]
new idle behaviour written, but not yet tested

**Comment by kragniz** [comment]
![screenshot from 2016-06-15 17-51-18](https://cloud.githubusercontent.com/assets/735008/16089203/f8f454ea-3321-11e6-8c2f-d93f84533a09.png)

Looks like it works okay in sails.
