### ISSUE TITLE
Invalidate wind data for a few seconds after tack

### ISSUE THREAD

**Issue by NicholasRostant** [abersailbot/dewi-behaviour#20]
To allow the wind averaging to catch up after a dramatic change. Tack beyond a close haul to prevent a shift in the wind putting her into irons.

**Comment by TomGC96** [comment]
This is unlikely to help much. At the moment, the apparent wind direction is calculated from the absolute wind direction, which is averaged. This means that the apparent wind direction will change according to the compass bearing, not the wind vane position. Therefore, this would not help us at this time.
