### ISSUE TITLE
Change all instances of 'relative wind' to be 'apparent wind' to remove ambiguity

### ISSUE THREAD

**Issue by Danyc0** [abersailbot/dewi-behaviour#23]
Relative is ambiguous because it could be relative to the boat, or the world. 'Apparent wind' does not have this issue.

**Comment by Danyc0** [comment]
Similar to #21 and should probably be fixed at the same time

**Comment by TomGC96** [comment]
This has been completed, but if any other places are seen to contain this name, they should be fixed.
